lang = {
    "zh_cn": {
        "company_name": "华虹",
        "company_name_margin_left": "font-size: 21px;margin-left: 455px;",

        "common_back_page": "上一页",
        "common_next_page": "下一页",
        "common_login": "登陆",
        "common_delete": "删除",
        "common_forget_pwd": "忘记密码?",
        "common_about_us": "关于我们",
        "common_about_us_up": "关于我们",
        "common_contact_us": "联系我们",
        "common_contact_us_up": "联系我们",
        "common_copyright": "© 2021 huahong.com",
        "common_account": "账号",
        "common_account_up": "账户",
        "common_password": "密码",
        "common_verify_code": "图形验证码",
        "common_account_detail": "账户详情",
        "common_historical_purchase": "历史购买",
        "common_historical_sample": "历史打样",
        "common_logout": "登出",
        "common_account_detail_up": "账户详情",
        "common_historical_purchase_up": "历史购买",
        "common_historical_sample_up": "历史打样",
        "common_add_products_up": "添加产品",
        "common_published_products_up": "已发布产品",
        "common_customer_account_info": "客户信息",
        "common_logout_up": "登出",
        "common_sample": "样品",
        "common_design_diagrams": "设计图",
        "common_reference_diagrams": "参考图",
        "common_new_arrivals": "当季新品",
        "common_all_categories": "总类别",
        "common_all_products": "全部产品",
        "common_sort": "排序",
        "common_latest_arrivals": "最新上架",
        "common_trending": "人气潮品",
        "common_price_low_high": "价格：从低到高",
        "common_price_high_low": "价格：从高到低",
        "common_import_from_computer": "从本地上传",
        "common_staff_email": "员工邮箱",
        "common_public": "公共",
        "common_add": "添加",
        "common_zh_name": "中文名",
        "common_en_name": "英文名",

        "header_nav_men": "男装",
        "header_nav_women": "女装",
        "header_nav_kids": "童装",
        "header_nav_everything_else": "其他",
        "header_nav_search": "搜索",
        "header_nav_lang": "中",
        "header_nav_wishlist": "愿望清单",
        "header_nav_shopping_bag": "购物袋",
        "header_nav_sample_bag": "打样袋",

        "about_us_first": "公司成立于2000年3月成立，是一家专门从事鞋类、箱包类、纺织类的出口型贸易公司。公司地址位于深圳南山。",
        "about_us_second": "公司拥有众多的合作工厂。并有极佳的销售平台。自主研发的多种鞋类款式，产品远销亚洲、欧洲、南北美洲，并得到广泛的赞誉与喜爱。二十多年在鞋类和箱包上的用心，华虹公司出口业务量领先于同类型的贸易公司，设计和质量都有保证。出口额在深圳南山区名列前茅。华虹公司是多年来海关认定的A类企业。",
        "about_us_third": "公司非常注重知识产权的保护，注册拥有各类自有商标品牌20种，均已通过国家知识产权局认定。",
        "about_us_forth": "在百年不遇的疫情中，华虹公司为湖北多家医院奉献爱心，希望能为社会排忧解难，为国家与人民生活发展贡献一份微薄之力。今后也将会力所能及地在慈善方面做尽最大的努力。",
        "about_us_fifth": "我公司全体员工本着以信誉求发展。努力使公司销售网络遍部全世界，争取涉足更宽广的地方。让世界上更多人能看到高质量的中国制造。",

        "contact_us_first": "深圳市华虹进出口贸易有限公司",
        "contact_us_second": "深圳市南山区东滨路4269号",
        "contact_us_third": "中泰天成南山主角大厦14楼",
        "contact_us_forth": "电话：86-755-26520270",
        "contact_us_fifth": "传真：86-755-26520160",

        "products_categories_shoes": "鞋履",
        "products_categories_bags": "包袋",
        "products_categories_accessories": "配饰",

        "color_colors": "颜色",
        "color_color": "颜色",
        "color_all_colors": "全部颜色",
        "color_brown": "棕色",
        "color_blue": "蓝色",
        "color_gray": "灰色",
        "color_white": "白色",
        "color_pink": "粉色",
        "color_purple": "紫色",
        "color_red": "红色",
        "color_green": "绿色",
        "color_yellow": "黄色",
        "color_black": "黑色",

        "account_info": "账户信息",
        "account_edit_details": "您可以编辑您的账户详情。",
        "account_change_pwd_tips": "您可以修改密码。",
        "account_last_name": "姓",
        "account_first_name": "名",
        "account_company_name": "公司名称",
        "account_old_password": "旧密码",
        "account_new_password": "新密码",
        "account_change_info": "修改信息",
        "account_change_password": "修改密码",

        "orders_check_preview_orders": "查看您的历史购买订单。",
        "orders_orders": "订单",
        "orders_date": "日期",
        "orders_total_amount": "总价",
        "orders_status": "状态",
        "orders_tracking_number": "物流编号",
        "orders_price": "价格",

        "products_brand": "品牌",
        "products_style": "款式",
        "products_description": "描述",
        "products_supplier_color": "供应商颜色",
        "products_material": "材质",
        "products_place_of_origin": "产地",
        "products_product_number": "产品编号",
        "products_factory_code": "工厂代码",
        "products_area": "所属地区",
        "products_currency": "货币",
        "products_price_range": "价格区间",
        "products_add_range": "添加区间",
        "products_category": "产品类别",
        "products_select_category": "选择产品",
        "products_size": "尺码",
        "products_choose_size": "选择尺码",
        "products_size_chart": "尺码表",
        "products_preview": "预览",
        "products_publish_the_sample": "发布样品",
        "products_qty": "数量",
        "products_price": "价格",
        "products_choose_color": "选择颜色",
        "products_choose_currency": "选择货币",
        "products_choose_area": "选择地区",
        "products_check_upload_area": "请和高级工作人员确认你是否可以上传商品到此地区。",
        "products_price_rmb": "人民币",
        "products_price_jpn": "日元",
        "products_price_eur": "欧元",
        "products_price_usd": "美元",

        "wishlist_title_info": "您可以在此页面管理您添加至愿望清单的产品。您可以删除或者把它们加入到购物袋和打样袋中下单。",
        "wishlist_add_to_bag": "添加至样品袋",

        "inner_login_success": "登陆成功",
        "inner_login_fail": "账号或密码错误",
        "inner_login_error_verify_code": "验证码错误，请重新输入",
        "inner_account_not_empty": "账号不允许为空",
        "inner_pwd_not_empty": "密码不允许为空",
        "inner_account_repeat_reset": "账户重复，请重新填写",
        "inner_name_repeat_reset": "名称重复，请重新填写",
        "inner_add_success": "添加成功",
        "inner_network_abnormal": "网络异常，请重试",
        "inner_zh_ch_repeat_reset": "中文重复，请重新填写",
        "inner_en_us_repeat_reset": "英文重复，请重新填写",
    },

    "en_us": {
        "company_name": "HUAHONG",
        "company_name_margin_left": "font-size: 21px;margin-left: 238px;",

        "common_back_page": "Previous",
        "common_next_page": "Next",
        "common_login": "LOG IN",
        "common_delete": "Delete",
        "common_forget_pwd": "Forget Password ?",
        "common_about_us": "About Us",
        "common_about_us_up": "ABOUT US",
        "common_contact_us": "Contact Us",
        "common_contact_us_up": "CONTACT US",
        "common_copyright": "© 2021 huahong.com",
        "common_account": "Account",
        "common_account_up": "ACCOUNT",
        "common_password": "Password",
        "common_verify_code": "Verify Code",
        "common_account_detail": "Account Details",
        "common_historical_purchase": "History Orders",
        "common_historical_sample": "History Samples",
        "common_logout": "Log Out",
        "common_account_detail_up": "ACCOUNT DETAILS",
        "common_historical_purchase_up": "HISTORY ORDERS",
        "common_historical_sample_up": "HISTORY SAMPLES",
        "common_add_products_up": "ADD PRODUCT",
        "common_published_products_up": "PUBLISHED PRODUCT",
        "common_customer_account_info": "CUSTOMER INFO",
        "common_logout_up": "LOG OUT",
        "common_sample": "SAMPLES",
        "common_design_diagrams": "DESIGNS",
        "common_reference_diagrams": "REFERENCES",
        "common_new_arrivals": "NEW ARRIVALS",
        "common_all_categories": "ALL CATEGORIES",
        "common_all_products": "ALL PRODUCTS",
        "common_sort": "SORT",
        "common_latest_arrivals": "Latest arrivals",
        "common_trending": "Trending",
        "common_price_low_high": "Price: Low-High",
        "common_price_high_low": "Price: High-Low",
        "common_import_from_computer": "Import from Computer",
        "common_staff_email": "STAFF EMAIL",
        "common_public": "Public",
        "common_add": "Add",
        "common_zh_name": "Chinese Name",
        "common_en_name": "English Name",

        "header_nav_men": "MEN",
        "header_nav_women": "WOMEN",
        "header_nav_kids": "KIDS",
        "header_nav_everything_else": "EVERYTHING ELSE",
        "header_nav_search": "SEARCH",
        "header_nav_lang": "EN",
        "header_nav_wishlist": "WISHLIST",
        "header_nav_shopping_bag": "SHOPPING BAG",
        "header_nav_sample_bag": "SAMPLE BAG",

        "about_us_first": "Shenzhen Huahong Import & Export Trade Company was founded in 2000 by Alice Wu. It is located in Nanshan, Shenzhen, China. Raised in an environment of the Chinese trading industry, Alice’s attraction to fashion accessories started at an early age. The company is specialized in exporting trade of shoes, bags and textiles.",
        "about_us_second": "Huahong has established long term cooperation with many qualified factories and excellent sales platforms. Huahong has its own design team to support customers with various needs, who much effort in designing and crafting. A variety of self-developed footwear styles are exported to Asia, Europe, North and South America and enjoy great popularity and praise.",
        "about_us_third": "With more than 20 years of dedication in shoes and bags, Huahong is ahead of other trading companies in export business volume. The design and quality are put into priority. Now this company is a class-A entreprise which has been recognized by Chinese customers.",
        "about_us_forth": "The company put great emphasize on protecting intellectual property rights. It has registered 20 kinds of its own trademark brands, which have all been recignized by the Staet Intellectual Property Office. ",
        "about_us_fifth": "In the unprecedented epidemic, Huahong Company has made donation to many hospitals in Hubei Province, hoping to solve the problems of society and contribute a modest contribution to the development of the country and people’s life. The company will continue to do our best in charity in the future. All employees of our company strive to expand the company’s sales network all over the world in line with the credibility of development. We look forward to expanding this high-quality China-made product known by people all over the world.",

        "contact_us_first": "Shenzhen HuaHong Import&Export Co.,Ltd.",
        "contact_us_second": "14Th/Fl. Nanshangzhujiao Bld., No.4269,DongBing",
        "contact_us_third": "Road, Nanshan.Shenzhen,China.",
        "contact_us_forth": "Tel: 86-755-26520270",
        "contact_us_fifth": "Fax: 86-755-26520160",

        "products_categories_shoes": "SHOES",
        "products_categories_bags": "BAGS",
        "products_categories_accessories": "ACCESSORIES",

        "color_colors": "COLORS",
        "color_color": "COLOR",
        "color_all_colors": "ALL COLORS",
        "color_brown": "Brown",
        "color_blue": "Blue",
        "color_gray": "Gray",
        "color_white": "White",
        "color_pink": "Pink",
        "color_purple": "Purple",
        "color_red": "Red",
        "color_green": "Green",
        "color_yellow": "Yellow",
        "color_black": "Black",

        "account_info": "ACCOUNT INFO",
        "account_edit_details": "Edit your account details.",
        "account_change_pwd_tips": "PASSWORD",
        "account_last_name": "Last Name",
        "account_first_name": "First Name",
        "account_company_name": "Company Name",
        "account_old_password": "Old Password",
        "account_new_password": "New Password",
        "account_change_info": "CHANGE YOUR INFO",
        "account_change_password": "CHANGE YOUR PASSWORD",

        "orders_check_preview_orders": "Check your preview's orders.",
        "orders_orders": "Orders",
        "orders_date": "Date",
        "orders_total_amount": "Total Amount",
        "orders_status": "Status",
        "orders_tracking_number": "Tracking Number",
        "orders_price": "Price",

        "products_brand": "BRAND",
        "products_style": "STYLE",
        "products_description": "DESCRIPTION",
        "products_supplier_color": "SUPPLIER COLOR",
        "products_material": "MATERIAL",
        "products_place_of_origin": "PLACE OF ORIGIN",
        "products_product_number": "PRODUCT NUMBER",
        "products_factory_code": "FACTORY CODE",
        "products_area": "AREA",
        "products_currency": "CURRENCY",
        "products_price_range": "PRICE RANGE",
        "products_add_range": "ADD RANGE",
        "products_category": "CATEGORY",
        "products_select_category": "Choose Category",
        "products_size": "SIZE",
        "products_choose_size": "Choose Size",
        "products_size_chart": "SIZE CHART",
        "products_preview": "PREVIEW",
        "products_publish_the_sample": "PUBLISH THE SAMPLE",
        "products_qty": "QTY",
        "products_price": "PRICE",
        "products_choose_color": "Choose Color",
        "products_choose_currency": "Choose Currency",
        "products_choose_area": "Choose Area",
        "products_check_upload_area": "Please check with the senior staff if you can upload to this area.",
        "products_price_rmb": "RMB",
        "products_price_jpn": "JPN",
        "products_price_eur": "EUR",
        "products_price_usd": "USD",

        "wishlist_title_info": "You can stay in this page to manage products that you added to wishlist. You can delete or add them to shopping bag or sample bag for placeing orders.",
        "wishlist_add_to_bag": "ADD TO SAMPLE BAG",

        "inner_login_success": "Login success",
        "inner_login_fail": "Incorrect username or password",
        "inner_login_error_verify_code": "The verification code is wrong",
        "inner_account_not_empty": "Account cannot be empty",
        "inner_pwd_not_empty": "Password cannot be empty",
        "inner_account_repeat_reset": "Duplicate account, please fill in again",
        "inner_name_repeat_reset": "Duplicate name, please fill in again",
        "inner_add_success": "Added successfully",
        "inner_network_abnormal": "The network is abnormal, please try again",
        "inner_zh_ch_repeat_reset": "Chinese repeat, please fill in again",
        "inner_en_us_repeat_reset": "English repeat, please fill in again",
    }
}
