FLASK_CONFIG = "development"
SECRET_KEY = "e8idu7666aa"
COOKIE_DURATION_DAYS = 1  # cookie保存时间
TEMP_FILE_DIR = "/app/static/uploads/temps/"
FILE_DIR = "/app/static/uploads/files/"
IMAGE_FILE_DIR = "/app/static/uploads/images/"
FILE_SUFFIX = ".tag"
FRAME_FILE_SUFFIX = ".txt"
DEFAULT_PASSWORD = "111111"
PAGE_LIMIT = 30
SEND_EMAIL = "609116848@qq.com"
