"""empty message

Revision ID: 4319e69e7190
Revises: 
Create Date: 2021-03-20 19:43:46.821575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4319e69e7190'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('VERB_ATTACHMENT',
    sa.Column('ID', sa.String(length=50), nullable=False, comment='ID'),
    sa.Column('CREATE_DATETIME', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('UPDATE_DATETIME', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('USER_ID', sa.String(length=50), nullable=False, comment='创建用户id'),
    sa.Column('DATA_ID', sa.String(length=50), nullable=False, comment='所属数据id'),
    sa.Column('NAME', sa.String(length=50), nullable=False, comment='附件名称'),
    sa.Column('PATH', sa.String(length=100), nullable=False, comment='附件路径'),
    sa.Column('SOURCE', sa.SmallInteger(), nullable=False, comment='附件来源， 0 默认是附件 1 图片'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_VERB_ATTACHMENT_CREATE_DATETIME'), 'VERB_ATTACHMENT', ['CREATE_DATETIME'], unique=False)
    op.create_table('VERB_CONFIG',
    sa.Column('ID', sa.String(length=50), nullable=False, comment='ID'),
    sa.Column('CREATE_DATETIME', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('UPDATE_DATETIME', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('NAME', sa.String(length=100), nullable=False, comment='配置名称'),
    sa.Column('KEY', sa.String(length=50), nullable=False, comment='配置键'),
    sa.Column('VALUE', sa.Text(), nullable=False, comment='配置值'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_VERB_CONFIG_CREATE_DATETIME'), 'VERB_CONFIG', ['CREATE_DATETIME'], unique=False)
    op.create_table('VERB_CONTACT',
    sa.Column('ID', sa.String(length=50), nullable=False, comment='ID'),
    sa.Column('CREATE_DATETIME', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('UPDATE_DATETIME', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('NAME', sa.String(length=50), nullable=False, comment='附件名称'),
    sa.Column('PHONE', sa.String(length=20), nullable=False, comment='手机号'),
    sa.Column('EMAIL', sa.String(length=60), nullable=False, comment='邮箱账号'),
    sa.Column('WE_CHAT', sa.String(length=30), nullable=False, comment='微信号'),
    sa.Column('QQ', sa.String(length=20), nullable=False, comment='QQ号'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_VERB_CONTACT_CREATE_DATETIME'), 'VERB_CONTACT', ['CREATE_DATETIME'], unique=False)
    op.create_index(op.f('ix_VERB_CONTACT_EMAIL'), 'VERB_CONTACT', ['EMAIL'], unique=False)
    op.create_table('VERB_DATA_LOG',
    sa.Column('ID', sa.String(length=50), nullable=False, comment='ID'),
    sa.Column('CREATE_DATETIME', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('USER_NAME', sa.String(length=100), nullable=False, comment='用户名称'),
    sa.Column('EMAIL', sa.String(length=60), nullable=False, comment='邮箱账号'),
    sa.Column('DESCRIPTION', sa.String(length=100), nullable=False, comment='备注'),
    sa.Column('ACTION', sa.String(length=200), nullable=False, comment='动作'),
    sa.Column('DATA', sa.String(length=50), nullable=False, comment='数据'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_VERB_DATA_LOG_CREATE_DATETIME'), 'VERB_DATA_LOG', ['CREATE_DATETIME'], unique=False)
    op.create_index(op.f('ix_VERB_DATA_LOG_EMAIL'), 'VERB_DATA_LOG', ['EMAIL'], unique=False)
    op.create_table('VERB_EMAIL',
    sa.Column('ID', sa.String(length=50), nullable=False, comment='ID'),
    sa.Column('CREATE_DATETIME', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('UPDATE_DATETIME', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('SENDER_ADDRESS', sa.String(length=100), nullable=False, comment='发件人邮件地址'),
    sa.Column('SENDER_NAME', sa.String(length=100), nullable=False, comment='发件人显示名'),
    sa.Column('SENDER_TITLE_PREFIX', sa.String(length=100), nullable=False, comment='发送邮件标题前缀'),
    sa.Column('HOST', sa.String(length=100), nullable=False, comment='服务器主机名'),
    sa.Column('PORT', sa.Integer(), nullable=False, comment='服务器端口'),
    sa.Column('USER_NAME', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('PASSWORD', sa.String(length=50), nullable=False, comment='密码'),
    sa.Column('IF_SSL', sa.Boolean(), nullable=False, comment='是否使用ssl， 0 默认不使用 1 使用'),
    sa.Column('IF_USED', sa.Boolean(), nullable=False, comment='是否被使用， 0 默认不使用 1 使用'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_VERB_EMAIL_CREATE_DATETIME'), 'VERB_EMAIL', ['CREATE_DATETIME'], unique=False)
    op.create_table('VERB_HOME_PAGE',
    sa.Column('ID', sa.String(length=50), nullable=False, comment='ID'),
    sa.Column('CREATE_DATETIME', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('UPDATE_DATETIME', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('TYPE', sa.Enum('HOME', 'PUBLICATIONS', 'CONTRIBUTORS'), nullable=False, comment='类别'),
    sa.Column('CONTENT', sa.Text(), nullable=False, comment='内容'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_VERB_HOME_PAGE_CREATE_DATETIME'), 'VERB_HOME_PAGE', ['CREATE_DATETIME'], unique=False)
    op.create_table('VERB_LINK',
    sa.Column('ID', sa.String(length=50), nullable=False, comment='ID'),
    sa.Column('CREATE_DATETIME', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('UPDATE_DATETIME', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('NAME', sa.String(length=50), nullable=False, comment='链接名称'),
    sa.Column('URL', sa.String(length=100), nullable=False, comment='链接地址'),
    sa.Column('SORT', sa.Integer(), nullable=False, comment='排序号(越小越靠前)'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_VERB_LINK_CREATE_DATETIME'), 'VERB_LINK', ['CREATE_DATETIME'], unique=False)
    op.create_table('VERB_ONLINE',
    sa.Column('ID', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('CREATE_DATETIME', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('LOGIN_NAME', sa.String(length=100), nullable=False, comment='登录名'),
    sa.Column('IP', sa.String(length=100), nullable=False, comment='登录IP'),
    sa.Column('TYPE', sa.String(length=200), nullable=False, comment='请求代理类型'),
    sa.Column('ACCESS_TOKEN', sa.String(length=50), nullable=False, comment='用户登录验证token'),
    sa.Column('IF_ONLINE', sa.Boolean(), nullable=False, comment='是否在线'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_VERB_ONLINE_ACCESS_TOKEN'), 'VERB_ONLINE', ['ACCESS_TOKEN'], unique=False)
    op.create_index(op.f('ix_VERB_ONLINE_CREATE_DATETIME'), 'VERB_ONLINE', ['CREATE_DATETIME'], unique=False)
    op.create_table('VERB_PRIVILEGE',
    sa.Column('ID', sa.String(length=50), nullable=False, comment='ID'),
    sa.Column('CREATE_DATETIME', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('UPDATE_DATETIME', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('NAME', sa.String(length=30), nullable=False, comment='命名'),
    sa.Column('TARGET', sa.String(length=200), nullable=False, comment='权限目标地址'),
    sa.Column('ACTION', sa.String(length=100), nullable=False, comment='动作'),
    sa.Column('TYPE', sa.Enum('controller', 'menu'), nullable=False, comment='权限类型：控制器、菜单'),
    sa.Column('DESCRIPTION', sa.String(length=200), nullable=False, comment='描述'),
    sa.Column('ICON_CLS', sa.String(length=100), nullable=False, comment='资源icon'),
    sa.Column('SORT', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('PARENT_ID', sa.String(length=50), nullable=True, comment='父资源ID'),
    sa.ForeignKeyConstraint(['PARENT_ID'], ['VERB_PRIVILEGE.ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('VERB_ROLE',
    sa.Column('ID', sa.String(length=50), nullable=False, comment='ID'),
    sa.Column('CREATE_DATETIME', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('UPDATE_DATETIME', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('NAME', sa.String(length=30), nullable=False, comment='权限角色名称'),
    sa.Column('DESCRIPTION', sa.String(length=200), nullable=False, comment='角色描述'),
    sa.Column('ICON_CLS', sa.String(length=100), nullable=False, comment='角色icon'),
    sa.Column('TYPE', sa.SmallInteger(), nullable=False, comment='角色创建类型0 自定义角色 1 系统角色'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('VERB_SPACE',
    sa.Column('ID', sa.String(length=50), nullable=False, comment='ID'),
    sa.Column('CREATE_DATETIME', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('UPDATE_DATETIME', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('NAME', sa.String(length=50), nullable=False, comment='空间名称'),
    sa.Column('DESCRIPTION', sa.String(length=200), nullable=False, comment='空间描述'),
    sa.Column('TAGS', sa.String(length=255), nullable=False, comment='空间标签，用英文逗号隔开'),
    sa.Column('VISIT_LEVEL', sa.Enum('private', 'public'), nullable=False, comment='访问级别：private,public'),
    sa.Column('IF_EXPORT', sa.Boolean(), nullable=False, comment='空间下数据是否允许导出'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('VERB_SYSTEM',
    sa.Column('ID', sa.String(length=50), nullable=False, comment='ID'),
    sa.Column('CREATE_DATETIME', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('UPDATE_DATETIME', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('SITE_NAME', sa.String(length=64), nullable=False, comment='网站名称'),
    sa.Column('ALLOW_LOGIN', sa.Boolean(), nullable=False, comment='是否允许登录'),
    sa.Column('COPY_RIGHT_INFO', sa.String(length=100), nullable=False, comment='版权信息'),
    sa.Column('IF_EMAIL', sa.Boolean(), nullable=False, comment='是否开启邮件通知'),
    sa.Column('VERSION', sa.String(length=10), nullable=False, comment='系统版本号'),
    sa.Column('TITLE', sa.String(length=30), nullable=False, comment='通知标题'),
    sa.Column('DESCRIPTION', sa.String(length=300), nullable=False, comment='通知内容'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('VERB_SYSTEM_LOG',
    sa.Column('ID', sa.String(length=50), nullable=False, comment='ID'),
    sa.Column('CREATE_DATETIME', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('LEVEL', sa.Enum('INFO', 'DEBUG', 'WARNING', 'ERROR'), nullable=False, comment='日志级别'),
    sa.Column('PATH', sa.String(length=100), nullable=False, comment='请求路径'),
    sa.Column('GET', sa.Text(), nullable=False, comment='get参数'),
    sa.Column('POST', sa.Text(), nullable=False, comment='post参数'),
    sa.Column('USER_NAME', sa.String(length=100), nullable=False, comment='用户名称'),
    sa.Column('USER_ID', sa.String(length=50), nullable=False, comment='用户ID'),
    sa.Column('MESSAGE', sa.String(length=100), nullable=False, comment='描述'),
    sa.Column('ACTION', sa.String(length=200), nullable=False, comment='动作'),
    sa.Column('IP', sa.String(length=100), nullable=False, comment='操作IP'),
    sa.Column('AGENT', sa.String(length=200), nullable=False, comment='用户代理'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_VERB_SYSTEM_LOG_CREATE_DATETIME'), 'VERB_SYSTEM_LOG', ['CREATE_DATETIME'], unique=False)
    op.create_table('VERB_ROLE_PRIVILEGE',
    sa.Column('ROLE_ID', sa.String(length=50), nullable=True),
    sa.Column('PRIVILEGE_ID', sa.String(length=50), nullable=True),
    sa.Column('CREATE_DATETIME', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['PRIVILEGE_ID'], ['VERB_PRIVILEGE.ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ROLE_ID'], ['VERB_ROLE.ID'], ondelete='CASCADE')
    )
    op.create_index(op.f('ix_VERB_ROLE_PRIVILEGE_PRIVILEGE_ID'), 'VERB_ROLE_PRIVILEGE', ['PRIVILEGE_ID'], unique=False)
    op.create_index(op.f('ix_VERB_ROLE_PRIVILEGE_ROLE_ID'), 'VERB_ROLE_PRIVILEGE', ['ROLE_ID'], unique=False)
    op.create_table('VERB_USER',
    sa.Column('ID', sa.String(length=50), nullable=False, comment='ID'),
    sa.Column('CREATE_DATETIME', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('LAST_DATETIME', sa.DateTime(), nullable=False, comment='最后登录时间'),
    sa.Column('UPDATE_DATETIME', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('EMAIL', sa.String(length=60), nullable=False, comment='邮箱账号'),
    sa.Column('_PWD', sa.String(length=100), nullable=False, comment='密码'),
    sa.Column('NAME', sa.String(length=100), nullable=False, comment='名称'),
    sa.Column('SEX', sa.String(length=1), nullable=False, comment='性别'),
    sa.Column('AGE', sa.Integer(), nullable=False, comment='年龄'),
    sa.Column('PHOTO', sa.String(length=200), nullable=False, comment='头像'),
    sa.Column('PHONE', sa.String(length=20), nullable=False, comment='手机号'),
    sa.Column('IF_LOGIN', sa.Boolean(), nullable=False, comment='是否允许登录'),
    sa.Column('WE_CHAT', sa.String(length=30), nullable=False, comment='微信号'),
    sa.Column('QQ', sa.String(length=20), nullable=False, comment='QQ号'),
    sa.Column('DESCRIPTION', sa.String(length=200), nullable=False, comment='备注'),
    sa.Column('LAST_IP', sa.String(length=15), nullable=False, comment='最后登录ip'),
    sa.Column('ROLE_ID', sa.String(length=50), nullable=True, comment='角色ID'),
    sa.ForeignKeyConstraint(['ROLE_ID'], ['VERB_ROLE.ID'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_VERB_USER_CREATE_DATETIME'), 'VERB_USER', ['CREATE_DATETIME'], unique=False)
    op.create_index(op.f('ix_VERB_USER_EMAIL'), 'VERB_USER', ['EMAIL'], unique=False)
    op.create_index(op.f('ix_VERB_USER_LAST_DATETIME'), 'VERB_USER', ['LAST_DATETIME'], unique=False)
    op.create_table('VERB_SPACE_USER',
    sa.Column('ID', sa.String(length=50), nullable=False, comment='ID'),
    sa.Column('SPACE_ID', sa.String(length=50), nullable=True),
    sa.Column('USER_ID', sa.String(length=50), nullable=True),
    sa.Column('CREATE_DATETIME', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('UPDATE_DATETIME', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('PRIVILEGE', sa.SmallInteger(), nullable=False, comment='空间成员操作权限 0 浏览者 1 编辑者 2 管理员'),
    sa.ForeignKeyConstraint(['SPACE_ID'], ['VERB_SPACE.ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['USER_ID'], ['VERB_USER.ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('VERB_SPACE_USER')
    op.drop_index(op.f('ix_VERB_USER_LAST_DATETIME'), table_name='VERB_USER')
    op.drop_index(op.f('ix_VERB_USER_EMAIL'), table_name='VERB_USER')
    op.drop_index(op.f('ix_VERB_USER_CREATE_DATETIME'), table_name='VERB_USER')
    op.drop_table('VERB_USER')
    op.drop_index(op.f('ix_VERB_ROLE_PRIVILEGE_ROLE_ID'), table_name='VERB_ROLE_PRIVILEGE')
    op.drop_index(op.f('ix_VERB_ROLE_PRIVILEGE_PRIVILEGE_ID'), table_name='VERB_ROLE_PRIVILEGE')
    op.drop_table('VERB_ROLE_PRIVILEGE')
    op.drop_index(op.f('ix_VERB_SYSTEM_LOG_CREATE_DATETIME'), table_name='VERB_SYSTEM_LOG')
    op.drop_table('VERB_SYSTEM_LOG')
    op.drop_table('VERB_SYSTEM')
    op.drop_table('VERB_SPACE')
    op.drop_table('VERB_ROLE')
    op.drop_table('VERB_PRIVILEGE')
    op.drop_index(op.f('ix_VERB_ONLINE_CREATE_DATETIME'), table_name='VERB_ONLINE')
    op.drop_index(op.f('ix_VERB_ONLINE_ACCESS_TOKEN'), table_name='VERB_ONLINE')
    op.drop_table('VERB_ONLINE')
    op.drop_index(op.f('ix_VERB_LINK_CREATE_DATETIME'), table_name='VERB_LINK')
    op.drop_table('VERB_LINK')
    op.drop_index(op.f('ix_VERB_HOME_PAGE_CREATE_DATETIME'), table_name='VERB_HOME_PAGE')
    op.drop_table('VERB_HOME_PAGE')
    op.drop_index(op.f('ix_VERB_EMAIL_CREATE_DATETIME'), table_name='VERB_EMAIL')
    op.drop_table('VERB_EMAIL')
    op.drop_index(op.f('ix_VERB_DATA_LOG_EMAIL'), table_name='VERB_DATA_LOG')
    op.drop_index(op.f('ix_VERB_DATA_LOG_CREATE_DATETIME'), table_name='VERB_DATA_LOG')
    op.drop_table('VERB_DATA_LOG')
    op.drop_index(op.f('ix_VERB_CONTACT_EMAIL'), table_name='VERB_CONTACT')
    op.drop_index(op.f('ix_VERB_CONTACT_CREATE_DATETIME'), table_name='VERB_CONTACT')
    op.drop_table('VERB_CONTACT')
    op.drop_index(op.f('ix_VERB_CONFIG_CREATE_DATETIME'), table_name='VERB_CONFIG')
    op.drop_table('VERB_CONFIG')
    op.drop_index(op.f('ix_VERB_ATTACHMENT_CREATE_DATETIME'), table_name='VERB_ATTACHMENT')
    op.drop_table('VERB_ATTACHMENT')
    # ### end Alembic commands ###
